CREATE DATABASE xlrelease OWNER xlrelease ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'en_US.UTF-8' TEMPLATE template0;
CREATE DATABASE xlarchive OWNER xlarchive ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'en_US.UTF-8' TEMPLATE template0;
